language: python

sudo: false

cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - travis_retry pip install -r requirements-test.txt

script:
  - pytest --cov-report term --cov=telega_compose

after_success:
  - bash <(curl -s https://codecov.io/bash)
